version: '3.8'

networks:
  server:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - server

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - server

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    networks:
      - server

  cipher:
    build:
      context: .
      dockerfile: ./cmd/cipher/Dockerfile
    tty: true
    volumes:
      - ./cmd/cipher/config.yaml:/configs/config.yaml:ro
    command:
      - -config-path
      - /configs/config.yaml
    ports:
      - 3307:3307

  cipher-postgres:
    image: postgres:16.7-alpine3.20
    container_name: cipher-postgres
    restart: on-failure:5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_SSL_MODE: disable
    ports:
      - 5431:5432

  user_db:
    image: postgres:16.7-alpine3.20
    container_name: user-management-postgres
    restart: on-failure:5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_SSL_MODE: disable
    ports:
      -  5432:5432