services:
  db:
    image: postgres:16.7-alpine3.20
    container_name: go_db
    restart: on-failure:5
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_SSL_MODE: "${POSTGRES_SSL_MODE}"
    ports:
      - "${POSTGRES_PORT}:5432"
