services:
  db:
    image: postgres:16.7-alpine3.20
    container_name: go_db
    restart: on-failure:5
    environment:
      POSTGRES_USER: null
      POSTGRES_PASSWORD: null
      POSTGRES_DB: null
      POSTGRES_HOST: null
      POSTGRES_PORT: null
      POSTGRES_SSL_MODE: null
    ports:
      - $POSTGRES_PORT:5432
