http:
  routers:
    api-router:
      rule: "PathPrefix(`/api/`)"
      service: api-service
      entryPoints:
        - web

  services:
    api-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:5001"
          - url: "http://127.0.0.1:5002"
          - url: "http://127.0.0.1:5003"
          - url: "http://127.0.0.1:5004"
          - url: "http://127.0.0.1:5005"