database:
  host: "cipher-postgres"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "mydb"
  sslmode: "disable"

kafka:
  brokers:
    - "kafka:9092"
  producer:
    topic: "cipher-updates"
  consumer:
    group: "cipher"

addr: ":3307"
logLevel: "trace"